name: chatapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  google_sign_in: ^5.2.3
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  freezed_annotation: ^1.1.0
  model: ^0.1.3
  json_annotation: ^4.4.0
  flutter_chat_ui: ^1.5.5
  image_picker: ^0.8.4+6
  uuid: ^3.0.5
  open_file: ^3.2.1
  file_picker: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^1.1.0
  json_serializable: ^6.1.3

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/